// src/app/app.component.ts
import { Component } from '@angular/core';
import { MenuController } from '@ionic/angular';
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})
export class AppComponent {
  public appPages = [
    { title: 'Inbox', url: '/folder/Inbox', icon: 'mail' },
    { title: 'Outbox', url: '/folder/Outbox', icon: 'paper-plane' },
    { title: 'Favorites', url: '/folder/Favorites', icon: 'heart' },
    { title: 'Archived', url: '/folder/Archived', icon: 'archive' },
    { title: 'Trash', url: '/folder/Trash', icon: 'trash' },
    { title: 'Spam', url: '/folder/Spam', icon: 'warning' },
  ];
  public labels = [ ];
  constructor(private menu: MenuController) {}

  openFirst() {
    this.menu.enable(true, 'first');
    this.menu.open('first');
  }

  openEnd() {
    this.menu.open('end');
  }

  openCustom() {
    this.menu.enable(true, 'custom');
    this.menu.open('custom');
  }

}

<ion-app>
  <ion-split-pane when="sm" content-id="main-content" style="--background: #202020;">
    <ion-menu  side="end" menuId="main-menu"   contentId="main-content" type="overlay"  style="--background: #202020;"     >
      <ion-content class="bordes" style="--background: #202020;"  >
        <ion-list id="inbox-list" class="lista_menu">
          <ion-list-header   >
            <ion-img src="assets/logomenu.png"  class="margen10botton"   ></ion-img>
          </ion-list-header>

          <ion-menu-toggle auto-hide="false"  lines="none"  class="lista_menu">
              <ion-item  routerLink="principal"  lines="none"  class="lista_menu" detail="false" routerLinkActive="selected">
                <ion-icon slot="start" name="home-outline"></ion-icon>
                <ion-label>Inicio</ion-label>
              </ion-item>


              <ion-item  routerLink="acerca"  lines="none"  class="lista_menu"  detail="false" routerLinkActive="selected">
                <ion-icon slot="start" name="person-outline"></ion-icon>
                <ion-label>Acerca de Junt@s
                </ion-label>
              </ion-item>

              <ion-item  routerLink="test"  lines="none" class="lista_menu"  detail="false" routerLinkActive="selected">
                <ion-icon slot="start" name="list-outline"></ion-icon>
                <ion-label>Test de violencia
                </ion-label>
              </ion-item>

              <ion-item  routerLink="hacer"  lines="none" class="lista_menu"  detail="false" routerLinkActive="selected">
                <ion-icon slot="start" name="help-circle-outline"></ion-icon>

                <ion-label>¿Qué puedo hacer?
                </ion-label>
              </ion-item>

              <ion-item  routerLink="apoyo"  lines="none"  class="lista_menu" detail="false" routerLinkActive="selected">
                <ion-icon slot="start" name="accessibility-outline"></ion-icon>
                <ion-label>Busca apoyo
                </ion-label>
              </ion-item>

              <ion-item  routerLink="testimonios"  lines="none"   class="lista_menu" detail="false" routerLinkActive="selected">
                <ion-icon slot="start"  name="chatbubble-ellipses-outline"></ion-icon>
                <ion-label>Testimonios
                </ion-label>
              </ion-item>

              <ion-item  routerLink="Acerca"  lines="none" class="lista_menu"  detail="false" routerLinkActive="selected">
                <ion-icon slot="start"  name="id-card-outline"></ion-icon>
                <ion-label>Contactos de emergencia
                </ion-label>
              </ion-item>



         </ion-menu-toggle>


        </ion-list>

        <ion-list id="labels-list" class="lista_menu">
          <ion-list-header> </ion-list-header>
          <ion-item  class="lista_menu"  routerLink="intro"  lines="none"  detail="false" routerLinkActive="selected">
            <ion-icon slot="start" name="ellipsis-horizontal-outline"></ion-icon>
            <ion-label>Intro
            </ion-label>
          </ion-item>

          <ion-item *ngFor="let label of labels" lines="none">
            <ion-icon slot="start" ios="bookmark-outline" md="bookmark-sharp"></ion-icon>
            <ion-label>{{ label }}</ion-label>
          </ion-item>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet id="main-content"></ion-router-outlet>
  </ion-split-pane>
</ion-app>

// src/App.vue
<template>
  <ion-app side="end"  end > 
    <ion-split-pane content-id="main-content"   side="right"   >
      <ion-menu  content-id="main-content" type="overlay" side="end" class="bordes">
        <ion-content>

           
          <div class="logomenu">
            <img src="../src/assets/logomenu.png"  >
          </div>
          <ion-list id="inbox-list">
            
  
            <ion-menu-toggle   auto-hide="false" v-for="(p, i) in appPages" :key="i" end>
              <ion-item @click="selectedIndex = i" router-direction="root" :router-link="p.url" lines="none" detail="false" class="hydrated" :class="{ selected: selectedIndex === i }">
                <ion-icon slot="start" :ios="p.iosIcon" :md="p.mdIcon"></ion-icon>
                <ion-label>{{ p.title }}</ion-label>
              </ion-item>
            </ion-menu-toggle>
          </ion-list>
  
          <ion-list id="labels-list">
            <ion-list-header> </ion-list-header>
  
            <ion-item v-for="(label, index) in labels" lines="none" :key="index">
              <ion-icon class="icon_menu" slot="and" :ios="bookmarkOutline" :md="bookmarkSharp"></ion-icon>
              <ion-label>{{ label }}</ion-label>
            </ion-item>
          </ion-list>
        </ion-content>
      </ion-menu>
      <ion-router-outlet id="main-content"></ion-router-outlet>
    </ion-split-pane>
  </ion-app>
</template>

<script lang="ts">
import { IonApp, IonContent, IonIcon, IonItem, IonLabel, IonList, IonListHeader, IonMenu, IonMenuToggle, IonNote, IonRouterOutlet, IonSplitPane } from '@ionic/vue';
import { defineComponent, ref } from 'vue';
import { useRoute } from 'vue-router';
import { archiveOutline, archiveSharp, bookmarkOutline, bookmarkSharp, heartOutline, heartSharp,
 mailOutline, mailSharp, paperPlaneOutline, paperPlaneSharp, trashOutline, trashSharp,
  warningOutline, warningSharp , home ,person ,clipboard , helpCircleOutline ,peopleOutline ,chatbubbleOutline ,atCircleOutline, locationOutline } from 'ionicons/icons';

export default defineComponent({
  name: 'App',
  components: {
    IonApp, 
    IonContent, 
    IonIcon, 
    IonItem, 
    IonLabel, 
    IonList, 
    IonListHeader, 
    IonMenu, 
    IonMenuToggle,  
    IonRouterOutlet, 
    IonSplitPane,
  },
  setup() {
    const selectedIndex = ref(0);
    const appPages = [
      {
        title: 'Inicio',
        url: '/inicio/',
        iosIcon: home,
        mdIcon: home
      },
      {
        title: 'Acerca de Junt@s',
        url: '/acerca/',
        iosIcon: person,
        mdIcon: person
      },
      {
        title: 'Test de Violencia',
        url: '/test/',
        iosIcon: clipboard ,
        mdIcon: clipboard
      },
      {
        title: '¿Qué puedo hacer?',
        url: '/folder/Archived',
        iosIcon: helpCircleOutline,
        mdIcon: helpCircleOutline
      },
      {
        title: 'Busca apoyo',
        url: '/folder/Trash',
        iosIcon: peopleOutline,
        mdIcon: peopleOutline
      },
      {
        title: 'Testimonios',
        url: '/folder/Spam',
        iosIcon: chatbubbleOutline,
        mdIcon: chatbubbleOutline
      },
      {
        title: 'Contactos de emergencia',
        url: '/folder/Spam',
        iosIcon: atCircleOutline,
        mdIcon: atCircleOutline
      },
      {
        title: 'Agencias Fiscalia',
        url: '/folder/Spam',
        iosIcon: locationOutline,
        mdIcon: locationOutline
      }
    ];
    const labels = ['Intro'];
    
    const path = window.location.pathname.split('folder/')[1];
    if (path !== undefined) {
      selectedIndex.value = appPages.findIndex(page => page.title.toLowerCase() === path.toLowerCase());
    }
    
    const route = useRoute();
    
    return { 
      selectedIndex,
      appPages, 
      labels,
      archiveOutline, 
      archiveSharp, 
      bookmarkOutline, 
      bookmarkSharp, 
      heartOutline, 
      heartSharp, 
      mailOutline, 
      mailSharp, 
      paperPlaneOutline, 
      paperPlaneSharp, 
      trashOutline, 
      trashSharp, 
      warningOutline, 
      warningSharp,
      isSelected: (url: string) => url === route.path ? 'selected' : ''
    }
  }
});
</script>

<style scoped>
ion-menu ion-content {
  --background: var(--ion-item-background, var(--ion-background-color, #202020));
}

ion-menu.md ion-content {
  --padding-start: 8px;
  --padding-end: 8px;
  --padding-top: 20px;
  --padding-bottom: 20px;
}

ion-menu.md ion-list {
  padding: 20px 0;
}

ion-menu.md ion-note {
  margin-bottom: 30px;
}

ion-menu.md ion-list-header,
ion-menu.md ion-note {
  padding-left: 10px;
}

ion-menu.md ion-list#inbox-list {
  border-bottom: 1px solid var(--ion-color-step-150, #d7d8da);
}

ion-menu.md ion-list#inbox-list ion-list-header {
  font-size: 22px;
  font-weight: 600;

  min-height: 20px;
}

ion-menu.md ion-list#labels-list ion-list-header {
  font-size: 16px;

  margin-bottom: 18px;

  color: #757575;

  min-height: 26px;
}

ion-menu.md ion-item {
  --padding-start: 10px;
  --padding-end: 10px;
  border-radius: 4px;
}

ion-menu.md ion-item.selected {
  --background: rgba(var(--ion-color-primary-rgb), 0.14);
}

ion-menu.md ion-item.selected ion-icon {
  color: var(--ion-color-primary);
}

ion-menu.md ion-item ion-icon {
  color: #616e7e;
}

ion-menu.md ion-item ion-label {
  font-weight: 500;
}

ion-menu.ios ion-content {
  --padding-bottom: 20px;
}

ion-menu.ios ion-list {
  padding: 20px 0 0 0;
}

ion-menu.ios ion-note {
  line-height: 24px;
  margin-bottom: 20px;
}

ion-menu.ios ion-item {
  --padding-start: 16px;
  --padding-end: 16px;
  --min-height: 50px;
}

ion-menu.ios ion-item.selected ion-icon {
  color: var(--ion-color-primary);
}

ion-menu.ios ion-item ion-icon {
  font-size: 24px;
  color: #73849a;
}

ion-menu.ios ion-list#labels-list ion-list-header {
  margin-bottom: 8px;
}

ion-menu.ios ion-list-header,
ion-menu.ios ion-note {
  padding-left: 16px;
  padding-right: 16px;
}

ion-menu.ios ion-note {
  margin-bottom: 8px;
}

ion-note {
  display: inline-block;
  font-size: 16px;

  color: var(--ion-color-medium-shade);
}

ion-item.selected {
  --color: var(--ion-color-primary);
}
</style>
